GET https://localhost:5001/api/food

###
GET https://localhost:5001/api/food/542

###
GET https://localhost:5001/api/food?pagenumber=1&pagesize=10

###
GET https://localhost:5001/api/food/search?Search=milk&pagenumber=1&pagesize=10

###
GET https://localhost:5001/api/food/category?categoryid=4&pagenumber=1&pagesize=10

###
GET https://localhost:5001/FoodEntry
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE1OTczMjEwNTUsIm5iZiI6MTU5NzIzNDY1NSwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9tYWNyb2J1ZGR5LmIyY2xvZ2luLmNvbS9jYTMxNTJiNi0zOTA5LTQ1ZDQtOWNjNi0zYmQxZmQzYmRmZjMvdjIuMC8iLCJzdWIiOiI1YzhlMDg3Yi03YWExLTRiMDAtOGE1OC1mZTBjYzM0ZGIyZTEiLCJhdWQiOiJlMjBmMmFlYy1kODkyLTQzMWYtOGJiZS1kZmU4MmVhZmQyMWYiLCJub25jZSI6ImRlZmF1bHROb25jZSIsImlhdCI6MTU5NzIzNDY1NSwiYXV0aF90aW1lIjoxNTk3MjM0NjU1LCJvaWQiOiI1YzhlMDg3Yi03YWExLTRiMDAtOGE1OC1mZTBjYzM0ZGIyZTEiLCJuYW1lIjoib21hcm8iLCJ0ZnAiOiJCMkNfMV9tYWNyb2J1ZGR5X3NpZ251cCJ9.h3WuaSrM9D2cED5COh2Ne7aHNx1ZLP2UHzq61XmWZpwy_1xiFBkESNmDf3kDfI9DuvM8GnlDL8mACDDCds4JIIauZF4pvSMsUeEUdhu5i90lSjQf9ZRr8cOmsnvv2tk1ISddu0H-gAAPo0Ws3bjZzGdoq4kSWRjkGXTb_cN0Hqse51TKlzoNYqSAfzd4k9VqSLoUwCzsTZq0VG_WZRL4VFhe_XD1mTaNHatUXjBKuChPcRQvS_A5exfGi4vfFkEhq56s1afjvm0tn5fOgUkbypJzZ-EYyFEYpq19qVLcwq3cfbEPURsq_CSvTJxAufwU6FENuARWNzaDD8__-Fje_g

###
POST https://localhost:5001/Food HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE1OTczMjEwNTUsIm5iZiI6MTU5NzIzNDY1NSwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9tYWNyb2J1ZGR5LmIyY2xvZ2luLmNvbS9jYTMxNTJiNi0zOTA5LTQ1ZDQtOWNjNi0zYmQxZmQzYmRmZjMvdjIuMC8iLCJzdWIiOiI1YzhlMDg3Yi03YWExLTRiMDAtOGE1OC1mZTBjYzM0ZGIyZTEiLCJhdWQiOiJlMjBmMmFlYy1kODkyLTQzMWYtOGJiZS1kZmU4MmVhZmQyMWYiLCJub25jZSI6ImRlZmF1bHROb25jZSIsImlhdCI6MTU5NzIzNDY1NSwiYXV0aF90aW1lIjoxNTk3MjM0NjU1LCJvaWQiOiI1YzhlMDg3Yi03YWExLTRiMDAtOGE1OC1mZTBjYzM0ZGIyZTEiLCJuYW1lIjoib21hcm8iLCJ0ZnAiOiJCMkNfMV9tYWNyb2J1ZGR5X3NpZ251cCJ9.h3WuaSrM9D2cED5COh2Ne7aHNx1ZLP2UHzq61XmWZpwy_1xiFBkESNmDf3kDfI9DuvM8GnlDL8mACDDCds4JIIauZF4pvSMsUeEUdhu5i90lSjQf9ZRr8cOmsnvv2tk1ISddu0H-gAAPo0Ws3bjZzGdoq4kSWRjkGXTb_cN0Hqse51TKlzoNYqSAfzd4k9VqSLoUwCzsTZq0VG_WZRL4VFhe_XD1mTaNHatUXjBKuChPcRQvS_A5exfGi4vfFkEhq56s1afjvm0tn5fOgUkbypJzZ-EYyFEYpq19qVLcwq3cfbEPURsq_CSvTJxAufwU6FENuARWNzaDD8__-Fje_g

###
PUT  https://localhost:5001/Food HTTP/1.1
content-type: application/json

{
    "id":4,
    "name": "sample",
    "protein":111,
    "carbohydrate":111,
    "fat":111
}

###

POST https://localhost:5001/FoodEntry HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE1OTczMjEwNTUsIm5iZiI6MTU5NzIzNDY1NSwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9tYWNyb2J1ZGR5LmIyY2xvZ2luLmNvbS9jYTMxNTJiNi0zOTA5LTQ1ZDQtOWNjNi0zYmQxZmQzYmRmZjMvdjIuMC8iLCJzdWIiOiI1YzhlMDg3Yi03YWExLTRiMDAtOGE1OC1mZTBjYzM0ZGIyZTEiLCJhdWQiOiJlMjBmMmFlYy1kODkyLTQzMWYtOGJiZS1kZmU4MmVhZmQyMWYiLCJub25jZSI6ImRlZmF1bHROb25jZSIsImlhdCI6MTU5NzIzNDY1NSwiYXV0aF90aW1lIjoxNTk3MjM0NjU1LCJvaWQiOiI1YzhlMDg3Yi03YWExLTRiMDAtOGE1OC1mZTBjYzM0ZGIyZTEiLCJuYW1lIjoib21hcm8iLCJ0ZnAiOiJCMkNfMV9tYWNyb2J1ZGR5X3NpZ251cCJ9.h3WuaSrM9D2cED5COh2Ne7aHNx1ZLP2UHzq61XmWZpwy_1xiFBkESNmDf3kDfI9DuvM8GnlDL8mACDDCds4JIIauZF4pvSMsUeEUdhu5i90lSjQf9ZRr8cOmsnvv2tk1ISddu0H-gAAPo0Ws3bjZzGdoq4kSWRjkGXTb_cN0Hqse51TKlzoNYqSAfzd4k9VqSLoUwCzsTZq0VG_WZRL4VFhe_XD1mTaNHatUXjBKuChPcRQvS_A5exfGi4vfFkEhq56s1afjvm0tn5fOgUkbypJzZ-EYyFEYpq19qVLcwq3cfbEPURsq_CSvTJxAufwU6FENuARWNzaDD8__-Fje_g

{
    "foodId" : 432,
    "amount":500
}